import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import SessionWrapper from '@/components/SessionWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',


  subsets: ['latin'],
});


const geistMono = Geist_Mono({
     variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'HR Dashboard',
  description: 'A Next.js HR performance dashboard generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    
  <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased dark:bg-gray-900 dark:text-white">
        <SessionWrapper>{children}</SessionWrapper>
           </body>
    </html>
  );
  
}